### ISSUE TITLE
Semistandard automatically format code --format support

### ISSUE THREAD

**Issue by joseluisq** [Flet/SublimeLinter-contrib-semistandard#2]
`-F  --format    Automatically format code. (using standard-format)`

In user shortcut

``` json
{ "keys": ["ctrl+alt+f"], "command": "semistandard_format" }
```

**Comment by ahmadnassri** [comment]
:+1:

**Comment by Flet** [comment]
This can be accomplished via @bcomnes StandardFormat on package control.

1) Make sure you have at least `semistandard` version 4.2.2... just update to the latest to be sure:

``` bash
npm install semistandard -g
```

2) Install **StandardFormat** from package control
3) Open the "user" package settings for "Standard Format"
- via command pallete: standard format settings user
- or via menu: Preference > Package Settings > Standard Format > Settings - User

4) Add a reference to `semistandard -F --stdin`:

``` js
{
  // set this to false if you don't want to format on save
  "format_on_save": true,
  "command": ["semistandard", "-F", "--stdin"],
}
```

5) Save the settings file.
6) Restart Sublime Text.

StandardFormat will also map <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>F</kbd> to format automatically. :)

**Comment by Flet** [comment]
added this text to install.txt and to README.md

**Comment by joseluisq** [comment]
Great ! :+1:
