### ISSUE TITLE
Support 'JavaScript (Babel)' syntax

### ISSUE THREAD

**Issue by bernharduw** [Flet/SublimeLinter-contrib-semistandard#3]
Just like the standard plugin, add JS (Babel) please: https://github.com/Flet/SublimeLinter-contrib-standard/commit/d57d85e01b2905d1d9e3028e1122533e02da7a25

**Comment by Flet** [comment]
Thanks for reporting!

Fixed in 1.0.2 https://github.com/Flet/SublimeLinter-contrib-semistandard/commit/75f2f6508f3ed9a8147ea32966fda1f7d7141fe9

Should be at package control in 30 minutes or so.

**Comment by bernharduw** [comment]
Working great, thanks a lot!
